In [1]:
import numpy as np
from itertools import product

In [2]:
def add(a,b):
    #addition is simple, XOR the binary representation of polynomials a and b
    result = np.zeros(8, dtype=int)
    for i in range(8):
        result[i] = np.mod(a[i]+b[i], 2)
    return result

In [3]:
def div_mod_2(divident, divisor):
    if len(divisor)>len(divident): raise Exception('Divisor is larger than divident')
    # calculates remainder of division
    while (len(divisor) <= len(divident)):
        for i in range(len(divisor)):
            divident[i] = np.mod(divident[i]+divisor[i], 2)
            
        while(divident[0] == 0): divident.pop(0)
        
    return divident

In [4]:
def multiply(a,b):
    reverse_a = np.flip(a) #reverse to use array positions as exponent
    reverse_b = np.flip(b)
    a_exp = np.asarray(reverse_a == 1).nonzero()[0] #exponents where bit is 1
    b_exp = np.asarray(reverse_b == 1).nonzero()[0]
    prod_exp = {}
    
    for x,y in product(a_exp, b_exp): #calculate product of polynomials a_exp and b_exp
        ab = x+y
        if ab in prod_exp.keys(): prod_exp[ab] += 1
        else: prod_exp[ab] = 1
        
    prod = np.zeros(15, dtype=int)
    for i in range(15): #represent the product as binary (each part mod 2)
        if i not in prod_exp.keys(): prod[i] = 0
        elif np.mod(prod_exp[i], 2) == 0: prod[i] = 0
        else: prod[i] = 1
            
    prod = np.flip(prod).tolist() #flip back to standard order
        
    divisor = "100011011" #x^8 + x^4 + x^3 + x +1
    divisor = [int(i) for i in divisor] #convert it to list of integers
    remainder = div_mod_2(prod, divisor)
    return remainder

In [5]:
def calculate(input_a, input_b):
    a = np.array(list('{:08b}'.format(input_a)), dtype=int) #convert to binary array
    b = np.array(list('{:08b}'.format(input_b)), dtype=int)
    mult_result = np.array(multiply(a,b))
    mult_result_decimal = int(np.array2string(mult_result, separator='')[1:-1], 2)
    add_result = add(a,b)
    add_result_decimal = int(np.array2string(add_result, separator='')[1:-1], 2)
    print(str(input_a) + ' + ' + str(input_b) + ' = ' + str(add_result_decimal))
    print(str(input_a) + ' * ' + str(input_b) + ' = ' + str(mult_result_decimal))
    print('--- Binary ---')
    print(str(a) + ' + ' + str(b) + ' = ' + str(add_result))
    print(str(a) + ' * ' + str(b) + ' = ' + str(mult_result))

In [6]:
calculate(5, 11)

5 + 11 = 14
5 * 11 = 39
--- Binary ---
[0 0 0 0 0 1 0 1] + [0 0 0 0 1 0 1 1] = [0 0 0 0 1 1 1 0]
[0 0 0 0 0 1 0 1] * [0 0 0 0 1 0 1 1] = [1 0 0 1 1 1]


In [7]:
calculate(83, 202)
print('-----------------------')
calculate(123, 41)
print('-----------------------')
calculate(15, 150)

83 + 202 = 153
83 * 202 = 1
--- Binary ---
[0 1 0 1 0 0 1 1] + [1 1 0 0 1 0 1 0] = [1 0 0 1 1 0 0 1]
[0 1 0 1 0 0 1 1] * [1 1 0 0 1 0 1 0] = [1]
-----------------------
123 + 41 = 82
123 * 41 = 119
--- Binary ---
[0 1 1 1 1 0 1 1] + [0 0 1 0 1 0 0 1] = [0 1 0 1 0 0 1 0]
[0 1 1 1 1 0 1 1] * [0 0 1 0 1 0 0 1] = [1 1 1 0 1 1 1]
-----------------------
15 + 150 = 153
15 * 150 = 19
--- Binary ---
[0 0 0 0 1 1 1 1] + [1 0 0 1 0 1 1 0] = [1 0 0 1 1 0 0 1]
[0 0 0 0 1 1 1 1] * [1 0 0 1 0 1 1 0] = [1 0 0 1 1]


In [6]:
calculate(53, 182)

53 + 182 = 131
53 * 182 = 252
--- Binary ---
[0 0 1 1 0 1 0 1] + [1 0 1 1 0 1 1 0] = [1 0 0 0 0 0 1 1]
[0 0 1 1 0 1 0 1] * [1 0 1 1 0 1 1 0] = [1 1 1 1 1 1 0 0]
